---
title: "RT-qPCR_analysis"
author: "Oliver Eyre"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ragg)

```

```{r}
data <- read.csv("Analysis_data.csv")

clean_data <- data %>% 
  mutate(Line = case_when(
   Line ==  "Pp-10-2" ~ "Pp-10-2",
   Line ==  "Pp-10-4" ~ "Pp-10-4",
   Line ==  "4pco-1" ~ "4pco",
   Line ==  "4pco-2" ~ "4pco",
   Line ==  "WT-1" ~ "AtPCO4-1",
   Line ==  "WT-2" ~ "AtPCO4-2",
   Line ==  "Col-0" ~ "Col-0"
  ))

```

```{r}
line_mean <- clean_data %>%
  mutate(exp_mean = X2..DDCt) %>% 
  mutate(exp_sd = ADH_St.Dev) %>% 
  group_by(Line) %>%
  summarise(
    n = n(),
    mean_exp = mean(exp_mean, na.rm = TRUE),
    sd_exp = sd(exp_mean, na.rm = TRUE),
    se_exp = sd_exp / sqrt(n)
  )

```

```{r}
line_colours <- c("4pco" = "brown", "AtPCO4-1" = "darkorange4", "AtPCO4-2" = "darkorange2", "Col-0" = "blue", "Pp-10-2" = "magenta4", "Pp-10-4" = "magenta3")

qPCR_figure <- ggplot(clean_data, aes(x=Line, y=X2..DDCt, color = Line)) + 
  geom_boxplot() + 
  geom_jitter(alpha = 0.3, show.legend = FALSE, position = position_jitter(width = 0.2, seed=0)) + 
  scale_colour_manual(values = line_colours) + 
  labs(x = "Plant Line", y = "Expression of Alcohol Dehydrogenase 1 (2^-DDCt)") +
theme_minimal()

qPCR_figure

agg_png("figures/RT-qPCR_figure.png", 
        width = 30,
        height = 20,
        units = "cm",
        res = 300,
        scaling = 2)

print(qPCR_figure)
dev.off()

```