---
title: "chromatogram_production"
author: "Oliver Eyre"
date: "2026-02-25"
output: html_document
---

---
title: "chromatogram_production"
author: "Oliver Eyre"
date: "2026-02-25"
output: html_document
---

This R script has been made to help create chromatogram graphs from data for use in a Masters thesis.

```{r Installing packages}
library(ggplot2)
library(dplyr)
library(scales)
library(readr)
library(tidyverse)
library(here)

```

```{r Cleaning data}
raw_data <- read.csv(here("His", "GcPCO_elution_18.11.2025 001.csv"))
colnames(raw_data) <- c("Conc_B_ml", "Conc_B_pct", "Fraction_ml", "Fraction_ID", "UV_ml", "UV_mAU", "unused")

summary(raw_data)

clean_data <- raw_data 

  clean_data$Conc_B_ml <- as.numeric(as.character(clean_data$Conc_B_ml))
  clean_data$Conc_B_pct <- as.numeric(as.character(clean_data$Conc_B_pct)) 
  clean_data$Fraction_ml <- as.numeric(as.character(clean_data$Fraction_ml)) 
  clean_data$Fraction_ID <- as.numeric(as.character(clean_data$Fraction_ID)) 
  clean_data$UV_ml <- as.numeric(as.character(clean_data$UV_ml)) 
  clean_data$UV_mAU <- as.numeric(as.character(clean_data$UV_mAU)) 
  
summary(clean_data)

tidy_data <- clean_data[, -which(names(clean_data) == "unused")]
```

```{r Creating subsetted data}
uv_data <- tidy_data %>%
  filter(!is.na(UV_ml) & !is.na(UV_mAU)) %>%
  distinct()

conc_b_data <- tidy_data %>%
  filter(!is.na(Conc_B_ml) & !is.na(Conc_B_pct)) %>%
  distinct()

fraction_lines <- tidy_data %>%
  filter(!is.na(Fraction_ml) & !is.na(Fraction_ID)) %>%
  distinct(Fraction_ID, Fraction_ml)

fractions_taken <- fraction_lines %>% 
  filter(Fraction_ID >11 & Fraction_ID <21)
```

```{r Setting data limits}
x_min <- min(fraction_lines$Fraction_ml)
x_max <- max(fraction_lines$Fraction_ml)

uv_max_fixed <- 2000 

conc_b_data <- conc_b_data %>%
  mutate(Conc_B_scaled = rescale(Conc_B_pct, to = c(0, uv_max_fixed)))
```

```{r Creating plot}
Gc_His_Plot <- ggplot() +
 # UV trace
  geom_line(data = uv_data, aes(x = UV_ml, y = UV_mAU), color = "magenta4", linewidth = 1.2) +
  
  # Conc B trace
  geom_line(data = conc_b_data, aes(x = Conc_B_ml, y = Conc_B_scaled), color = "cyan4", linewidth = 1.2) +
  
  #Indicate which fractions were taken forward for further purification.
  geom_vline(data = fractions_taken, aes(xintercept = Fraction_ml), linetype = "dotted", color = "black") +
  
  scale_x_continuous(name = "Volume Eluted (ml)",
                     breaks = seq(30, 105, 5),
                     limits = c(x_min, x_max)) +
  
  # Y-axis scales
  scale_y_continuous(
    name = "UV Absorbance (mAU)",
    limits = c(0, uv_max_fixed),
    breaks = seq(0, uv_max_fixed, by = 500),
    sec.axis = sec_axis(
      ~ rescale(., from = c(0, uv_max_fixed), to = range(conc_b_data$Conc_B_pct)),
      name = "Concentration of Elution Buffer (%)"
    )
  ) +
  
  # Theme styling
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    
     # Titles
    axis.title.x = element_text(size = 18, margin = margin(t = 15)),
    axis.title.y.left = element_text(color = "magenta4", size = 16),
    axis.title.y.right = element_text(color = "cyan4", size = 16),
    
    # Tick labels
    axis.text.x = element_text(angle = 90, vjust = 0.5, size = 19),
    axis.text.y.left = element_text(color = "magenta4", size = 19),
    axis.text.y.right = element_text(color = "cyan4", size = 19),
    
    plot.margin = margin(10, 10, 10, 10)
  )

print(Gc_His_Plot)
```

```{r Printing Figure}

agg_png("figures/GcPCO_His_Chromatogram.png", 
        width = 40,
        height = 20,
        units = "cm",
        res = 300,
        scaling = 1)

print(Gc_His_Plot)
dev.off()

```