---
title: "Root_Phenotype_Analysis"
author: "Oliver Eyre"
date: "`r Sys.Date()`"
output: html_document
---

---
title: "Root_Phenotype_Analysis"
author: "Oliver Eyre"
date: "2026-05-01"
output: html_document
---

```{r}
library(tidyverse)
library(tidyr)
library(ggplot2)
library(mclust)
library(lme4)
library(lmerTest)
library(emmeans)
library(ragg)
```

```{r}

raw_data <- read.csv("root_phenotype_data.csv")
summary(raw_data)

clean_data <- raw_data[
  complete.cases(raw_data$Day_7_Root_Length_mm,
                 raw_data$Day_14_Root_Length_mm),] %>% 
  mutate(Line = case_when(
    Line == "Col-0" ~ "Col-0",
    Line == "Pp-10-2" ~ "Pp-10-2",
    Line == "Pp-10-4" ~ "Pp-10-4",
    Line == "4pco_2" ~ "4pco",
    Line == "4pco" ~ "4pco",
    Line == "3pco" ~ "AtPCO4-1",
    Line == "3pco_2" ~ "AtPCO4-2"))

#Only includes samples where data collected for both day 7 and day 14, and also changes names where necessary. 
#Had 2 distinct groups for 4pco, but given subsequent analysis, is unhelpful.

clean_pco_data <- clean_data %>% 
  subset(Line == "4pco")

```

```{r}


Day_7_boxplot <- ggplot(clean_data, aes(x=Line, y=Day_7_Root_Length_mm)) + geom_boxplot() + geom_jitter(alpha = 0.3, show.legend = FALSE, position = position_jitter(width = 0.2, seed=0))
Day_7_boxplot

Day_14_boxplot <- ggplot(clean_data, aes(x=Line, y=Day_14_Root_Length_mm)) + geom_boxplot() + geom_jitter(alpha = 0.3, show.legend = FALSE, position = position_jitter(width = 0.2, seed=0))
Day_14_boxplot

```

```{r}

Day7_model <- Mclust(clean_pco_data$Day_7_Root_Length_mm)
summary(Day7_model) #Creating model to determine whether there are two statistically distinct subpopulations

Day7_model$BIC
plot(Day7_model$BIC) #Looking at BIC values to determine which model (with 1, 2, 3 etc populations) fits data best at day 7.
table(Day7_model$classification) #Shows how many clusters the model has fitted. In this case, has fitted 8 clusters.
boxplot(clean_pco_data$Day_7_Root_Length_mm ~ Day7_model$classification) #Shows root lengths for each cluster.

Day7_model_2 <- Mclust(clean_pco_data$Day_7_Root_Length_mm, G = 2) #'G = 2 limits the model to two clusters, reflecting germinated vs non-germinated plants.
Day7_model_2$BIC
plot(Day7_model_2$BIC) 
table(Day7_model_2$classification)
boxplot(clean_pco_data$Day_7_Root_Length_mm ~ Day7_model_2$classification)
```

```{r}
Day14_model <- Mclust(clean_pco_data$Day_14_Root_Length_mm)
summary(Day14_model)

Day14_model$BIC #Looking at BIC values to see which model fits better for Day 14 data.
plot(Day14_model$BIC) #Shows peak at 2 clusters with equal variance - supports hypothesis of two separate populations.

table(Day14_model$classification)
boxplot(clean_pco_data$Day_14_Root_Length_mm ~ Day14_model$classification)
```

```{r}
#Generating a model where the function can choose how many clusters there are.
combined_model <- Mclust(cbind(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm))
summary(combined_model)

combined_model$BIC
plot(combined_model$BIC)
table(combined_model$classification)
plot(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm, col = combined_model$classification)

plot(combined_model, what = "classification")
fit2 <- Mclust(cbind(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm), G = 2)
summary(fit2)

fit4 <- Mclust(cbind(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm), G = 4)
summary(fit4)

fit2$bic
fit4$bic

fit4_table <- aggregate(clean_pco_data[, c("Day_7_Root_Length_mm", "Day_14_Root_Length_mm")],
          by = list(cluster = fit4$classification),
          mean)
fit4_table

fit2_table <- aggregate(clean_pco_data[, c("Day_7_Root_Length_mm", "Day_14_Root_Length_mm")],
          by = list(cluster = fit2$classification),
          mean)
fit2_table

plot(fit2, what = "classification")
plot(fit4, what = "classification") #There is significant overlap between different clusters, suggesting only 2 biologically relevant subgroups with phenotypic variation between them Therefore, will continue applying two subgroup limit.

plot(fit2, what = "uncertainty")
plot(fit4, what = "uncertainty")

summary(fit2$uncertainty)
summary(fit4$uncertainty)

clean_pco_data$Growth =
  clean_pco_data$Day_14_Root_Length_mm -
  clean_pco_data$Day_7_Root_Length_mm

boxplot(clean_pco_data$Growth ~ fit4$classification)
boxplot(clean_pco_data$Growth ~ fit2$classification)

```

```{r}

combined_model_2 <- Mclust(cbind(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm), G = 2 ) #G = 2 limits subgroups to two. 
summary(combined_model_2)

combined_model_2$BIC
plot(combined_model_2$BIC)
table(combined_model_2$classification)

aggregate(clean_pco_data[, c("Day_7_Root_Length_mm", "Day_14_Root_Length_mm")],
          by = list(cluster = combined_model_2$classification),
          mean)
plot(combined_model_2, what = "classification")

GMM_results_plot <- plot(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$Day_14_Root_Length_mm, col = combined_model_2$classification)

agg_png("figures/GMM_figure.png", 
        width = 20,
        height = 15,
        units = "cm",
        res = 300,
        scaling = 1.5)

print(GMM_results_plot)
dev.off()

```

```{r}

clean_pco_data$cluster <- combined_model_2$classification

tapply(clean_pco_data$Day_7_Root_Length_mm, clean_pco_data$cluster, summary)
tapply(clean_pco_data$Day_14_Root_Length_mm, clean_pco_data$cluster, summary)
plot(clean_pco_data$Day_7_Root_Length_mm,
     clean_pco_data$Day_14_Root_Length_mm,
     col = clean_pco_data$cluster,
     pch = 16) 

clean_pco_data$growth <- clean_pco_data$Day_14_Root_Length_mm -
                     clean_pco_data$Day_7_Root_Length_mm

boxplot(clean_pco_data$growth ~ clean_pco_data$cluster)
```

```{r}
all(clean_pco_data$Sample == clean_data$Sample)

cluster_data <- merge(clean_data,
                    clean_pco_data[, c("Sample", "cluster")],
                    by = "Sample",
                    all.x = TRUE)

cluster_data$Phenotype <- factor(cluster_data$cluster,
                             levels = c(1, 2),
                             labels = c("Fast growth", "Slow growth"))
```

```{r}
library(ggplot2)

ggplot(cluster_data, aes(x = Line,
                        y = Day_14_Root_Length_mm,
                        fill = Phenotype)) +
  geom_boxplot() +
  theme_minimal() +
  labs(fill = "Growth group")

ggplot(cluster_data, aes(Day_7_Root_Length_mm,
                       Day_14_Root_Length_mm,
                       color = Phenotype)) +
  geom_point() +
  facet_wrap(~ Line) +
  theme_minimal()

ggplot(cluster_data, aes(cluster, Day_14_Root_Length_mm, fill = Line)) +
  geom_boxplot() +
  theme_minimal()
```

```{r}
long_data <- pivot_longer(cluster_data,
                          cols = c(Day_7_Root_Length_mm, Day_14_Root_Length_mm),
                          names_to = "Day",
                          values_to = "Root_Length")

long_data <- long_data %>% 
  mutate(Day = case_when(
   Day == "Day_7_Root_Length_mm" ~ "7",
   Day == "Day_14_Root_Length_mm" ~ "14"
  ))

long_data$Day <- factor(long_data$Day,
                        levels = c("7",  "14"))

root_model <- lmer(Root_Length ~ Line * Day + (1 | Sample), data = long_data)

summary(root_model)
anova(root_model)

emm_growth <- emmeans(root_model, ~ Line * Day)
contrast(emm_growth, interaction = "pairwise", adjust = "tukey")

line_colours <- c("4pco" = "brown", "4pco_AtPCO4" = "darkorange2", "Col-0" = "blue", "Pp-10-2" = "magenta4", "Pp-10-4" = "magenta3")
phenotype_fill <- c("Fast growth" = "gray4", "Slow growth" = "gray")

ANOVA_fig <- ggplot(long_data, aes(x = Day, y = Root_Length, color = Line)) +
  stat_summary(fun = mean, geom = "line", aes(group = Line)) +
  stat_summary(fun = mean, geom = "point") +
  labs(x = "Day", y = "Mean root length (mm)") +
  scale_color_manual(values = line_colours) +
  scale_fill_manual(values = phenotype_fill) +
  theme_minimal()

agg_png("figures/anova_figure.png", 
        width = 20,
        height = 15,
        units = "cm",
        res = 300,
        scaling = 1.5)

print(ANOVA_fig)
dev.off()
```

```{r}
line_mean <- cluster_data %>%
  mutate(Day_7_mean = Day_7_Root_Length_mm) %>% 
  mutate(Day_14_mean = Day_14_Root_Length_mm) %>% 
  group_by(Line) %>%
  summarise(
    n = n(),
    mean_7 = mean(Day_7_mean, na.rm = TRUE),
    sd_7 = sd(Day_7_mean, na.rm = TRUE),
    se_7 = sd_7 / sqrt(n),
    mean_14 = mean(Day_14_mean, na.rm = TRUE),
    sd_14 = sd(Day_14_mean, na.rm = TRUE),
    se_14 = sd_14 / sqrt(n)
  ) #Table of results detailing mean growth per line at both timepoints, alongside SD and SE.

line_growth_mean <- cluster_data %>%
  mutate(Growth =
           Day_14_Root_Length_mm -
           Day_7_Root_Length_mm) %>%
  group_by(Line) %>%
  summarise(
    n = n(),
    mean_growth = mean(Growth, na.rm = TRUE),
    sd_growth = sd(Growth, na.rm = TRUE),
    se_growth = sd_growth / sqrt(n)
  ) 

phenotype_mean <- cluster_data %>%
  mutate(Day_7_mean = Day_7_Root_Length_mm) %>% 
  mutate(Day_14_mean = Day_14_Root_Length_mm) %>% 
  group_by(Phenotype) %>%
  summarise(
    n = n(),
    mean_7 = mean(Day_7_mean, na.rm = TRUE),
    sd_7 = sd(Day_7_mean, na.rm = TRUE),
    se_7 = sd_7 / sqrt(n),
    mean_14 = mean(Day_14_mean, na.rm = TRUE),
    sd_14 = sd(Day_14_mean, na.rm = TRUE),
    se_14 = sd_14 / sqrt(n)
  )

phenotype__growth_mean <- cluster_data %>%
  mutate(Growth =
           Day_14_Root_Length_mm -
           Day_7_Root_Length_mm) %>%
  group_by(Phenotype) %>%
  summarise(
    n = n(),
    mean_growth = mean(Growth, na.rm = TRUE),
    sd_growth = sd(Growth, na.rm = TRUE),
    se_growth = sd_growth / sqrt(n)
  ) 

```

```{r}

line_colours <- c("4pco" = "brown", "AtPCO4-1" = "darkorange4", "AtPCO4-2" = "darkorange2", "Col-0" = "blue", "Pp-10-2" = "magenta4", "Pp-10-4" = "magenta3")
phenotype_fill <- c("Fast growth" = "gray4", "Slow growth" = "gray")

day7_figure <- ggplot(cluster_data, aes(Line, Day_7_Root_Length_mm, color = Line, fill = Phenotype)) +
  geom_boxplot() +
  labs(x = "Genotype", y = "Day 7 Root Length (mm)", col = "Genotype") +
  geom_jitter(alpha = 0.3, position = position_jitter(width = 0.2, seed=0)) +
  scale_colour_manual(values = line_colours) +
  scale_fill_manual(values = phenotype_fill) +
  theme_minimal()

day7_figure

day14_figure <- ggplot(cluster_data, aes(Line, Day_14_Root_Length_mm, color = Line, fill = Phenotype)) +
  geom_boxplot() +
  labs(x = "Genotype", y = "Day 14 Root Length (mm)", col = "Genotype", fill) +
  geom_jitter(alpha = 0.3, position = position_jitter(width = 0.2, seed=0)) +
  scale_colour_manual(values = line_colours) +
  scale_fill_manual(values = phenotype_fill) +
  theme_minimal()

day14_figure

agg_png("figures/day7_figure.png", 
        width = 30,
        height = 20,
        units = "cm",
        res = 300,
        scaling = 2)

print(day7_figure)
dev.off()

agg_png("figures/day14_figure.png", 
        width = 30,
        height = 20,
        units = "cm",
        res = 300,
        scaling = 2)

print(day14_figure)
dev.off()

```
