---
title: "RF_120min_Analysis"
author: "Oliver Eyre"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
library(tidyverse)
library(tidyr)
library(ggplot2)
library(ragg)
```

```{r}
Pp_S_raw_data <- read.csv("Pp-S_10.03.csv")
  Pp_S_raw_data$PlateName <- as.character(Pp_S_raw_data$PlateName)
  Pp_S_raw_data$Fraction <- as.numeric(Pp_S_raw_data$Fraction)
  Pp_S_raw_data$X..Oxidation <- parse_number(Pp_S_raw_data$X..Oxidation)
  
  class(Pp_S_raw_data$PlateName)
  class(Pp_S_raw_data$Fraction)

Pp_S_clean <- Pp_S_raw_data[complete.cases(Pp_S_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate1" ~ "PpPCO (Early peak)")) %>% 
     select(-Row, -Column, -X1442.74, -X1474.74, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate)

Pp_S_clean$Turnover <- ((Pp_S_clean$X..Oxidation*0.009)/0.00264)/100 #*100 as parse_number makes R treat % like a normal number, not a decimal, so is inflating turnover by 100.

Pp_L_raw_data <- read.csv("Pp-L_10.03.csv")
    Pp_L_raw_data$PlateName <- as.character(Pp_L_raw_data$PlateName)
    Pp_L_raw_data$Fraction <- as.numeric(Pp_L_raw_data$Fraction)
    Pp_L_raw_data$X..Oxidation <- parse_number(Pp_L_raw_data$X..Oxidation)
  
  class(Pp_L_raw_data$PlateName)
  class(Pp_L_raw_data$Fraction)

Pp_L_clean <- Pp_L_raw_data[complete.cases(Pp_L_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate2" ~ "PpPCO (Late peak)")) %>% 
     select(-Row, -Column, -X1442.73, -X1474.73, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate)

Pp_L_clean$Turnover <- ((Pp_L_clean$X..Oxidation*0.009)/0.00262)/100

Pu_raw_data <- read.csv("Pu_10.03.csv")
  Pu_raw_data$PlateName <- as.character(Pu_raw_data$PlateName)
  Pu_raw_data$Fraction <- as.numeric(Pu_raw_data$Fraction)
  Pu_raw_data$X..Oxidation <- parse_number(Pu_raw_data$X..Oxidation)
  
  class(Pu_raw_data$PlateName)

Pu_clean <- Pu_raw_data[complete.cases(Pu_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate1" ~ "PuPCO")) %>% 
  select(-Row, -Column, -X1442.73, -X1474.73, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate, -X.1, -X.2, -X.3, -X.4, -X.5)

Pu_clean$Turnover <- ((Pu_clean$X..Oxidation*0.009)/0.00387)/100

Gc_raw_data <- read.csv("Gc_10.03.csv")
 Gc_raw_data$PlateName <- as.character(Gc_raw_data$PlateName)
 Gc_raw_data$Fraction <- as.numeric(Gc_raw_data$Fraction)
 Gc_raw_data$X..Oxidation <- parse_number(Gc_raw_data$X..Oxidation)
  
  class(Gc_raw_data$PlateName)

Gc_clean <- Gc_raw_data[complete.cases(Gc_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate2" ~ "GcPCO")) %>% 
  select(-Row, -Column, -X1442.73, -X1474.73, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate)

Gc_clean$Turnover <- ((Gc_clean$X..Oxidation*0.009)/0.00276)/100

Fs_L_raw_data <- read.csv("Fs-L_10.03.csv")
  Fs_L_raw_data$PlateName <- as.character(Fs_L_raw_data$PlateName)
  Fs_L_raw_data$Fraction <- as.numeric(Fs_L_raw_data$Fraction)
  Fs_L_raw_data$X..Oxidation <- parse_number(Fs_L_raw_data$X..Oxidation)
  
  class(Fs_L_raw_data$PlateName)

Fs_L_clean <- Fs_L_raw_data[complete.cases(Fs_L_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate2" ~ "FsPCO (Late peak)")) %>% 
     select(-Row, -Column, -X1442.74, -X1474.74, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate) 

Fs_L_clean$Turnover <- ((Fs_L_clean$X..Oxidation*0.009)/0.00254)/100

At4_raw_data <- read.csv("At4_10.03.csv")
  At4_raw_data$PlateName <- as.character(At4_raw_data$PlateName)
  At4_raw_data$Fraction <- as.numeric(At4_raw_data$Fraction)
  At4_raw_data$X..Oxidation <- parse_number(At4_raw_data$X..Oxidation)
  
  class(At4_raw_data$PlateName)

At4_clean <- At4_raw_data[complete.cases(At4_raw_data$Timepoint),] %>% 
   mutate(PlateName = case_when(
PlateName == "Plate1" ~ "AtPCO4")) %>% 
     select(-Row, -Column, -X1442.74, -X1474.74, -Injection.Time..sec., -Turnover, -X, -mg.enzyme, -uM_substrate)
At4_clean$Turnover <- ((Fs_L_clean$X..Oxidation*0.009)/0.00264)/100

```

```{r}

combined_data <- bind_rows(Pp_S_clean, Pp_L_clean, Pu_clean, Gc_clean, Fs_L_clean, At4_clean) 

clean_combined_data <- combined_data %>% 
  subset(EM.MM0 == "EM")
  
mean_data <- combined_data %>% 
  subset(EM.MM0 == "EM") %>% 
  group_by(PlateName, Timepoint) %>% 
  summarise (
    mean_t = mean(Turnover, na.rm = TRUE),
    sd_t = sd(Turnover, na.rm = TRUE),
    n = n(),
    se_t = sd_t / sqrt(n),
    .groups = "drop")

```

```{r}
enzyme_colours <- c("PpPCO (Early peak)" = "blue", "PpPCO (Late peak)" = "deepskyblue2", "GcPCO" = "magenta4", "PuPCO" = "darkorchid1", "FsPCO (Late peak)" = "darkorange2", "AtPCO4" = "darkgoldenrod2")

line_graph <- ggplot(mean_data, aes(x = Timepoint, y = mean_t, xmax = 120, col = PlateName)) +
  geom_line(size = 0.6) +
  labs(x = "Time (minutes)", y = expression("Mean Turnover (" * mu * "mol substrate/mg enzyme)"), col = "Enzyme") +
  geom_errorbar(aes(ymin = mean_t-se_t,
                    ymax = mean_t+se_t),
                    width = 1.5) +
   geom_jitter(data = clean_combined_data,
              aes(x = Timepoint,
                  y = Turnover, 
                  col = PlateName),
              width = 0.4,
              alpha = 0.5,
              size = 1,
              seed = 0,
              inherit.aes = FALSE) +
  scale_colour_manual(values = enzyme_colours) +
  scale_x_continuous(limits = c(0, 120), breaks = c(0, 20, 40, 60, 80, 100, 120)) +
  coord_cartesian(xlim = c(0, 120)) +
  theme_minimal() +
  theme(text = element_text(family = "Arial"))

line_graph

agg_png("figures/120min.png", 
        width = 30,
        height = 20,
        units = "cm",
        res = 300,
        scaling = 2)

print(line_graph)
dev.off()


```